window.google||(google={});if(!window.google.update)google.update={};google.update.c=[];function _GU_OnloadHandlerAdd(b,a){var c=google.update.c.length;if(typeof a=="number")if(a<c&&a>=0)c=a;google.update.c.splice(c,0,b)}function _GU_OnloadBody(b){var a=window.google.update.c;if(a)for(var c=0;c<a.length;++c)try{a[c](b)}catch(d){}}
function _GU_getPlatform(){if(window.google.update.d)return window.google.update.d;window.google.update.d=navigator.platform=="Win32"?"win":navigator.platform=="WinCE"?"wince":/linux/i.test(navigator.platform)?"linux":/mac/i.test(navigator.platform)?"mac":"win";return window.google.update.d}
function _GU_getBrowserId(){if(window.google.update.a)return window.google.update.a;window.google.update.a=0;if(navigator.userAgent.indexOf("Opera")!=-1)window.google.update.a=0;else if(navigator.userAgent.indexOf("Firefox")!=-1)window.google.update.a=3;else if(navigator.userAgent.indexOf("MSIE")!=-1)if(navigator.userAgent.indexOf("Windows CE")!=-1)window.google.update.a=0;else{if(navigator.userAgent.indexOf("PPC")==-1&&navigator.userAgent.indexOf("Smartphone")==-1)window.google.update.a=2}else if(navigator.userAgent.indexOf("Chrome")!=
-1)window.google.update.a=4;else if(navigator.userAgent.indexOf("Safari")!=-1)window.google.update.a=0;return window.google.update.a}function _GU_setCookie(b,a,c){b=b+"="+escape(a);if(-1!=c){a=new Date;a.setMinutes(a.getMinutes()+c);b+=";expires="+a.toUTCString()}document.cookie=b}function _GU_setSessionCookie(b,a){_GU_setCookie(b,a,-1)}
function _GU_getCookie(b){if(document.cookie){var a=document.cookie.indexOf(b+"=");if(a!=-1&&(a==0||document.cookie.substring(a-2,a-1)==";")){a=a+b.length+1;b=document.cookie.indexOf(";",a);if(b==-1)b=document.cookie.length;return unescape(document.cookie.substring(a,b))}}return""}function _GU_removeCookie(b){_GU_setCookie(b,"",0)}function _GU_areCookiesSupported(){_GU_setCookie("test","1",1);var b=_GU_getCookie("test")=="1";_GU_removeCookie("test");return b}
function _GU_initIid(){function b(){function c(){var d=65536;d=Math.floor(Math.random()*d);for(d=d.toString(16);d.length<4;)d="0"+d;return d.toUpperCase()}return"{"+c()+c()+"-"+c()+"-"+c()+"-"+c()+"-"+c()+c()+c()+"}"}var a=_GU_getCookie("iid");if(a)window.google.update.b=a;else if(_GU_areCookiesSupported()){window.google.update.b=b();_GU_setSessionCookie("iid",window.google.update.b)}else window.google.update.b="{11112222-3333-4444-5555-666677778888}"}
function _GU_getIid(){window.google.update.b||_GU_initIid();return window.google.update.b}function _GU_createAppInfo(b,a,c,d){var f={};f.guid=b;f.name=a;f.needsAdmin=c;f.customParams=d;return f}
function GU_BuildTag(b,a){a||(a="");for(var c="",d=0;d<b.length;++d){if(d==0){c+="appguid="+b[d].guid;c+=a}else c+="&appguid="+b[d].guid;c+="&appname="+encodeURIComponent(b[d].name).replace(/~/g,"%7E").replace(/\!/g,"%21").replace(/\*/g,"%2A").replace(/\(/g,"%28").replace(/\)/g,"%29").replace(/\'/g,"%27");c+="&needsadmin="+b[d].needsAdmin;if(b[d].customParams)c+=b[d].customParams}return c}
function GU_buildGlobalExtra(b,a){var c="&iid="+_GU_getIid()+"&lang="+b+"&browser="+_GU_getBrowserId()+"&usagestats=";c+=a?"1":"0";return c}
function _GU_isClickOnceAvailable(){function b(a){function c(e,i){var g=0,h=0,k=0;do{h=g<e.length?Number(e[g]):0;k=g<i.length?Number(i[g]):0;++g}while((g<e.length||g<i.length)&&h==k);if(h<k)return-1;if(h>k)return 1;return 0}var d=navigator.userAgent.match(/\.NET CLR [0-9.]+/g);if(d==null||d.length==0)return false;a=a.split(".");if(a.length==0)return false;for(var f=0;f<d.length;++f){var j=d[f].match(/\.NET CLR ([0-9.]+)/);if(!(j==null||j.length!=2)){j=j[1].split(".");if(j.length>0&&c(a,j)<=0)return true}}return false}
if(window.location.search.indexOf("noclickonce")>=0)return false;if(2!=_GU_getBrowserId())return false;return b("2.0.0")}function _GU_isOneClickAvailable(){return window.google.update&&window.google.update.oneclick}function _GU_SetupOneClick(){_GU_SetupOneClickVersions(["8"])}
function _GU_SetupOneClickVersions(b){function a(e){var i=document.createElement("object");i.type="application/x-vnd.google.oneclickctrl."+e;i.id="OneClickCtrl";document.body.appendChild(i);return i}if(!(window.google.update&&window.google.update.oneclick))if("win"==_GU_getPlatform()){for(var c=0;c<b.length;++c){var d=b[c];try{new ActiveXObject("Google.OneClickCtrl."+d);window.google.update.oneclickPlugin_=a(d)}catch(f){var j=navigator.mimeTypes["application/x-vnd.google.oneclickctrl."+d];if(j&&j.enabledPlugin)window.google.update.oneclickPlugin_=
a(d)}if(window.google.update.oneclickPlugin_)break}if(!(!window.google.update.oneclickPlugin_||window.location.search.indexOf("nooneclick")>=0))if(!window.google.update.oneclick)window.google.update.oneclick={getOneClickVersion:function(){try{return window.google.update.oneclickPlugin_.GetOneClickVersion()}catch(e){return-1}},install:function(e,i,g,h,k){var n="http://tools.google.com";n+="/service/update2/installping";g=GU_buildGlobalExtra(i,g);g='"'+GU_BuildTag(e,g)+'"';for(c=0;c<e.length;++c){var l=
n;l+="?appid="+encodeURIComponent(e[c].guid);l+="&lang="+encodeURIComponent(i);l+="&iid="+encodeURIComponent(_GU_getIid());l+="&installsource=oneclick";var o=new Image;o.src=l}e="/install "+g;try{window.google.update.oneclickPlugin_.Install(e,h,k)}catch(m){h=0;try{h=m.number;if(!h){e="";e=m.message?m.message:m;h=parseInt(e,"0x"==e.substring(0,2)?16:10)}}catch(p){}if(isNaN(h)||0==h)h=-2;k(h)}},getInstalledVersion:function(e,i){var g="";try{g=window.google.update.oneclickPlugin_.GetInstalledVersion(e,
i)}catch(h){}return g}}}}function _GU_buildDlPath(b,a,c,d,f){a=GU_buildGlobalExtra(a,c);b=GU_BuildTag(b,a);return d+"/tag/s/"+encodeURIComponent(b)+f}function _GU_buildDlPathNoTag(b,a,c,d,f){return d+f}function _GU_buildClickOncePath(b,a,c,d,f){a=GU_buildGlobalExtra(a,c);b=GU_BuildTag(b,a);return d+f+"?"+encodeURIComponent(b)};
